/**
 * obullxl@gmail.com
 */
package com.github.obullxl.jeesite.dal.mybatis;

import com.github.obullxl.jeesite.dal.dao.TopicDAO;

import com.github.obullxl.jeesite.dal.query.TopicQuery;
import java.util.Map;
import com.github.obullxl.jeesite.dal.dto.TopicDTO;
import java.util.List;
import org.springframework.dao.DataAccessException;
import java.util.HashMap;


import com.github.obullxl.ticket.TicketService;
import com.github.obullxl.ticket.api.TicketException;
import com.github.obullxl.ticket.fmt.TicketEncode;
import com.github.obullxl.lang.Profiler;

/**
 * A mybatis based implementation of DAO interface <tt>com.github.obullxl.jeesite.dal.dao.TopicDAO</tt>.
 *
 * Generated by <tt>atom-dalgen</tt> on Thu Jan 02 11:56:15 CST 2014.
 *
 * @author obullxl@gmail.com
 */
public class MyBatisTopicDAO extends org.mybatis.spring.support.SqlSessionDaoSupport implements TopicDAO {
	/** TicketID */
	private TicketService ticketService;
	
	public void setTicketService(TicketService ticketService) {
		this.ticketService = ticketService;
	}
	
	public TicketService getTicketService() {
        return ticketService;
    }

	/** Ticket Encoder */
	private TicketEncode ticketEncode;
	
	public void setTicketEncode(TicketEncode ticketEncode) {
		this.ticketEncode = ticketEncode;
	}

	/**
	 *  Insert one <tt>TopicDTO</tt> object to DB table <tt>atom_topic</tt>, return primary key
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into atom_topic(id,flag,catg,link_url,media_url,visit_cnt,reply_cnt,title,summary,content,gmt_create,gmt_modify) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)</tt>
	 *
	 *	@param topic
	 *	@return String
	 *	@throws DataAccessException
	 */	 
    public String insert(TopicDTO topic) throws DataAccessException{
	Profiler.enter("DAO: ATOM-TOPIC.insert");
	try {
    	if (topic == null) {
    		throw new IllegalArgumentException("Can't insert a null data object into db.");
    	}
    	
        try {
            topic.setId(this.ticketEncode.encode(this.ticketService.nextValue()));
        } catch (TicketException e) {
            throw new RuntimeException("Set PrimaryKey exception.", e);
        }

        this.getSqlSession().insert("ATOM-TOPIC.insert", topic);

        return topic.getId();
	} finally {
		Profiler.release();
	}
}

	/**
	 *  Query DB table <tt>atom_topic</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from atom_topic where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return TopicDTO
	 *	@throws DataAccessException
	 */	 
    public TopicDTO find(String id) throws DataAccessException{
	Profiler.enter("DAO: ATOM-TOPIC.find");
	try {

        return this.getSqlSession().selectOne("ATOM-TOPIC.find", id);

	} finally {
		Profiler.release();
	}
}
	/**
	 *  Query DB table <tt>atom_topic</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from atom_topic</tt>
	 *
	 *	@return List<TopicDTO>
	 *	@throws DataAccessException
	 */	 
    public List<TopicDTO> findAll() throws DataAccessException{
	Profiler.enter("DAO: ATOM-TOPIC.findAll");
	try {

        return this.getSqlSession().selectList("ATOM-TOPIC.findAll", null);

	} finally {
		Profiler.release();
	}
}
	/**
	 *  Query DB table <tt>atom_topic</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from atom_topic where (catg = 'catg')</tt>
	 *
	 *	@param catgs
	 *	@return TopicDTO
	 *	@throws DataAccessException
	 */	 
    public TopicDTO findCatgOne(List catgs) throws DataAccessException{
	Profiler.enter("DAO: ATOM-TOPIC.findCatgOne");
	try {

        return this.getSqlSession().selectOne("ATOM-TOPIC.findCatgOne", catgs);

	} finally {
		Profiler.release();
	}
}
	/**
	 *  Query DB table <tt>atom_topic</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from atom_topic where ((id = 'ID') AND (catg = 'CATG') AND (title = 'TITLE'))</tt>
	 *
	 *	@param args
	 *	@return List<TopicDTO>
	 *	@throws DataAccessException
	 */	 
    public List<TopicDTO> findFuzzy(TopicQuery args) throws DataAccessException{
	Profiler.enter("DAO: ATOM-TOPIC.findFuzzy");
	try {

        return this.getSqlSession().selectList("ATOM-TOPIC.findFuzzy", args);

	} finally {
		Profiler.release();
	}
}
	/**
	 *  Query DB table <tt>atom_topic</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select COUNT(*) from atom_topic where ((id = 'ID') AND (catg = 'CATG') AND (title = 'TITLE'))</tt>
	 *
	 *	@param args
	 *	@return long
	 *	@throws DataAccessException
	 */	 
    public long findFuzzyCount(TopicQuery args) throws DataAccessException{
	Profiler.enter("DAO: ATOM-TOPIC.findFuzzyCount");
	try {

	    Long retObj = (Long) this.getSqlSession().selectOne("ATOM-TOPIC.findFuzzyCount", args);

		if (retObj == null) {
		    return 0;
		} else {
		    return retObj.longValue();
		}

	} finally {
		Profiler.release();
	}
}
	/**
	 *  Query DB table <tt>atom_topic</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from atom_topic where (catg = 'CATG')</tt>
	 *
	 *	@param catgs
	 *	@param size
	 *	@return List<TopicDTO>
	 *	@throws DataAccessException
	 */	 
    public List<TopicDTO> findTopVisit(List catgs, int size) throws DataAccessException{
	Profiler.enter("DAO: ATOM-TOPIC.findTopVisit");
	try {
        Map<String, Object> param = new HashMap<String, Object>();

        param.put("catgs", catgs);
        param.put("size", new Integer(size));

        return this.getSqlSession().selectList("ATOM-TOPIC.findTopVisit", param);

	} finally {
		Profiler.release();
	}
}
	/**
	 *  Query DB table <tt>atom_topic</tt> for records.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from atom_topic where (catg = 'CATG')</tt>
	 *
	 *	@param catgs
	 *	@param size
	 *	@return List<TopicDTO>
	 *	@throws DataAccessException
	 */	 
    public List<TopicDTO> findTopReply(List catgs, int size) throws DataAccessException{
	Profiler.enter("DAO: ATOM-TOPIC.findTopReply");
	try {
        Map<String, Object> param = new HashMap<String, Object>();

        param.put("catgs", catgs);
        param.put("size", new Integer(size));

        return this.getSqlSession().selectList("ATOM-TOPIC.findTopReply", param);

	} finally {
		Profiler.release();
	}
}
	/**
	 *  Update DB table <tt>atom_topic</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update atom_topic set flag=?, catg=?, link_url=?, media_url=?, title=?, summary=?, content=? where (id = ?)</tt>
	 *
	 *	@param topic
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int update(TopicDTO topic) throws DataAccessException{
	Profiler.enter("DAO: ATOM-TOPIC.update");
	try {
    	if (topic == null) {
    		throw new IllegalArgumentException("Can't update by a null data object.");
    	}


        return this.getSqlSession().update("ATOM-TOPIC.update", topic);
	} finally {
		Profiler.release();
	}
}
	/**
	 *  Update DB table <tt>atom_topic</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update atom_topic set visit_cnt='visit+1', gmt_modify='NOW' where (id = '1')</tt>
	 *
	 *	@param id
	 *	@param count
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateVisit(String id, int count) throws DataAccessException{
	Profiler.enter("DAO: ATOM-TOPIC.updateVisit");
	try {
        Map<String, Object> param = new HashMap<String, Object>();

        param.put("id", id);
        param.put("count", new Integer(count));

        return this.getSqlSession().update("ATOM-TOPIC.updateVisit", param);
	} finally {
		Profiler.release();
	}
}
	/**
	 *  Update DB table <tt>atom_topic</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update atom_topic set reply_cnt='reply+1', gmt_modify='NOW' where (id = '1')</tt>
	 *
	 *	@param id
	 *	@param count
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int updateReply(String id, int count) throws DataAccessException{
	Profiler.enter("DAO: ATOM-TOPIC.updateReply");
	try {
        Map<String, Object> param = new HashMap<String, Object>();

        param.put("id", id);
        param.put("count", new Integer(count));

        return this.getSqlSession().update("ATOM-TOPIC.updateReply", param);
	} finally {
		Profiler.release();
	}
}
	/**
	 *  Delete records from DB table <tt>atom_topic</tt>.
	 *
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from atom_topic where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return int
	 *	@throws DataAccessException
	 */	 
    public int delete(String id) throws DataAccessException{
	Profiler.enter("DAO: ATOM-TOPIC.delete");
	try {

        return this.getSqlSession().delete("ATOM-TOPIC.delete", id);
	} finally {
		Profiler.release();
	}
}
}
